### ISSUE TITLE
ramalama 0.7.4 still using 0.7.0 ramalama-rag image

### ISSUE THREAD

**Issue by edhaynes** [containers/ramalama#1192]
### Issue Description

I tried out ramalama 0.7.4 installed via pip3 on mac and fedora 41 - in both cases ramalama rag is pulling older image 0.7.0 that still has the init_empty_ weights bug documented in https://github.com/containers/ramalama/issues/1157 and fixed in ramalama-rag:0.7.4

### Steps to reproduce the issue

Steps to reproduce the issue
1.ramalama rag doc.pdf quay.io/ehaynes/ragstuff
2.
3.

### Describe the results you received

Describe the results you received
File "/usr/local/lib/python3.11/site-packages/transformers/modeling_utils.py", line 3736, in get_init_context
    init_contexts = [no_init_weights(), init_empty_weights()]
                                        ^^^^^^^^^^^^^^^^^^
NameError: name 'init_empty_weights' is not defined
-> Cannot close object, library is destroyed. This may cause a memory leak!
Error: Command '['podman', 'run', '--rm', '-v', '/Users/ehaynes/Downloads/SCTE_35_2022b.pdf:/docs//Users/ehaynes/Downloads/SCTE_35_2022b.pdf:ro,z', '-v', '/Users/ehaynes/Downloads/RamaLama_rag_s3t6ag2h/vectordb:/output:z', '**quay.io/ramalama/ramalama-rag:0.7**', 'doc2rag', '/output', '/docs/']' returned non-zero exit status 1.

### Describe the results you expected

Describe the results you expected

expected ramalama 7.4 to use image quay.io/ramalama/ramalama-rag:0.7.4 not 0.7.0

if  run command with --image=quay.io/ramalama/ramalama-rag:0.7.4 it avoids the init_empty_weights bug in the 0.7.0 image

### ramalama info output

```yaml
If you are unable to run ramalama info for any reason, please provide the ramalama version, operating system and its version and the architecture you are running.
{
    "Accelerator": "none",
    "Engine": {
        "Info": {
            "Client": {
                "APIVersion": "5.4.1",
                "BuildOrigin": "pkginstaller",
                "Built": 1741718260,
                "BuiltTime": "Tue Mar 11 14:37:40 2025",
                "GitCommit": "b79bc8afe796cba51dd906270a7e1056ccdfcf9e",
                "GoVersion": "go1.24.1",
                "Os": "darwin",
                "OsArch": "darwin/arm64",
                "Version": "5.4.1"
            },
            "host": {
                "arch": "arm64",
                "buildahVersion": "1.38.1",
                "cgroupControllers": [
                    "cpuset",
                    "cpu",
                    "io",
                    "memory",
                    "pids",
                    "rdma",
                    "misc"
                ],
                "cgroupManager": "systemd",
                "cgroupVersion": "v2",
                "conmon": {
                    "package": "conmon-2.1.12-3.fc41.aarch64",
                    "path": "/usr/bin/conmon",
                    "version": "conmon version 2.1.12, commit: "
                },
                "cpuUtilization": {
                    "idlePercent": 99.49,
                    "systemPercent": 0.12,
                    "userPercent": 0.39
                },
                "cpus": 6,
                "databaseBackend": "sqlite",
                "distribution": {
                    "distribution": "fedora",
                    "variant": "coreos",
                    "version": "41"
                },
                "eventLogger": "journald",
                "freeLocks": 2032,
                "hostname": "localhost.localdomain",
                "idMappings": {
                    "gidmap": null,
                    "uidmap": null
                },
                "kernel": "6.12.7-200.fc41.aarch64",
                "linkmode": "dynamic",
                "logDriver": "journald",
                "memFree": 8591785984,
                "memTotal": 19463438336,
                "networkBackend": "netavark",
                "networkBackendInfo": {
                    "backend": "netavark",
                    "dns": {
                        "package": "aardvark-dns-1.13.1-1.fc41.aarch64",
                        "path": "/usr/libexec/podman/aardvark-dns",
                        "version": "aardvark-dns 1.13.1"
                    },
                    "package": "netavark-1.13.1-1.fc41.aarch64",
                    "path": "/usr/libexec/podman/netavark",
                    "version": "netavark 1.13.1"
                },
                "ociRuntime": {
                    "name": "crun",
                    "package": "crun-1.19.1-1.fc41.aarch64",
                    "path": "/usr/bin/crun",
                    "version": "crun version 1.19.1\ncommit: 3e32a70c93f5aa5fea69b50256cca7fd4aa23c80\nrundir: /run/crun\nspec: 1.0.0\n+SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +LIBKRUN +WASM:wasmedge +YAJL"
                },
                "os": "linux",
                "pasta": {
                    "executable": "/usr/bin/pasta",
                    "package": "passt-0^20241211.g09478d5-1.fc41.aarch64",
                    "version": "pasta 0^20241211.g09478d5-1.fc41.aarch64-pasta\nCopyright Red Hat\nGNU General Public License, version 2 or later\n  <https://www.gnu.org/licenses/old-licenses/gpl-2.0.html>\nThis is free software: you are free to change and redistribute it.\nThere is NO WARRANTY, to the extent permitted by law.\n"
                },
                "remoteSocket": {
                    "exists": true,
                    "path": "unix:///run/podman/podman.sock"
                },
                "rootlessNetworkCmd": "pasta",
                "security": {
                    "apparmorEnabled": false,
                    "capabilities": "CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT",
                    "rootless": false,
                    "seccompEnabled": true,
                    "seccompProfilePath": "/usr/share/containers/seccomp.json",
                    "selinuxEnabled": true
                },
                "serviceIsRemote": true,
                "slirp4netns": {
                    "executable": "/usr/bin/slirp4netns",
                    "package": "slirp4netns-1.3.1-1.fc41.aarch64",
                    "version": "slirp4netns version 1.3.1\ncommit: e5e368c4f5db6ae75c2fce786e31eef9da6bf236\nlibslirp: 4.8.0\nSLIRP_CONFIG_VERSION_MAX: 5\nlibseccomp: 2.5.5"
                },
                "swapFree": 0,
                "swapTotal": 0,
                "uptime": "74h 54m 13.00s (Approximately 3.08 days)",
                "variant": "v8"
            },
            "plugins": {
                "authorization": null,
                "log": [
                    "k8s-file",
                    "none",
                    "passthrough",
                    "journald"
                ],
                "network": [
                    "bridge",
                    "macvlan",
                    "ipvlan"
                ],
                "volume": [
                    "local"
                ]
            },
            "registries": {
                "search": [
                    "docker.io"
                ]
            },
            "store": {
                "configFile": "/usr/share/containers/storage.conf",
                "containerStore": {
                    "number": 12,
                    "paused": 0,
                    "running": 0,
                    "stopped": 12
                },
                "graphDriverName": "overlay",
                "graphOptions": {
                    "overlay.imagestore": "/usr/lib/containers/storage",
                    "overlay.mountopt": "nodev,metacopy=on"
                },
                "graphRoot": "/var/lib/containers/storage",
                "graphRootAllocated": 98899800064,
                "graphRootUsed": 39025475584,
                "graphStatus": {
                    "Backing Filesystem": "xfs",
                    "Native Overlay Diff": "false",
                    "Supports d_type": "true",
                    "Supports shifting": "true",
                    "Supports volatile": "true",
                    "Using metacopy": "true"
                },
                "imageCopyTmpDir": "/var/tmp",
                "imageStore": {
                    "number": 72
                },
                "runRoot": "/run/containers/storage",
                "transientStore": false,
                "volumePath": "/var/lib/containers/storage/volumes"
            },
            "version": {
                "APIVersion": "5.3.2",
                "Built": 1737504000,
                "BuiltTime": "Tue Jan 21 19:00:00 2025",
                "GitCommit": "",
                "GoVersion": "go1.23.4",
                "Os": "linux",
                "OsArch": "linux/arm64",
                "Version": "5.3.2"
            }
        },
        "Name": "podman"
    },
    "Image": "quay.io/ramalama/ramalama",
    "Runtime": "llama.cpp",
    "Store": "/Users/ehaynes/.local/share/ramalama",
    "UseContainer": true,
    "Version": "0.7.4"
}
```

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting
