### ISSUE TITLE
ramalama rag fails with RHEL 9 networking guide PDF

### ISSUE THREAD

**Issue by tyll** [containers/ramalama#1221]
### Issue Description

ramalama rag Red_Hat_Enterprise_Linux-9-Configuring_and_managing_networking-en-US.pdf localhost/RHEL9networking-rag fails without actionable information

### Steps to reproduce the issue

Steps to reproduce the issue
1. wget https://docs.redhat.com/en/documentation/red_hat_enterprise_linux/9/pdf/configuring_and_managing_network
ing/Red_Hat_Enterprise_Linux-9-Configuring_and_managing_networking-en-US.pdf
2. ramalama rag Red_Hat_Enterprise_Linux-9-Configuring_and_managing_networking-en-US.pdf localhost/RHEL9networki
ng-rag 
3.

### Describe the results you received

Downloading detection model, please wait. This may take several minutes depending upon your network connection.
Downloading recognition model, please wait. This may take several minutes depending upon your network connection.
/usr/bin/doc2rag:46: DeprecationWarning: Use contextualize() instead.
  doc_text = chunker.serialize(chunk=chunk)
Error: Command '['podman', 'run', '--rm', '-v', '/home/till/Red_Hat_Enterprise_Linux-9-Configuring_and_managing_networking-en-US.pdf:/docs//home/till/Red_Hat_Enterprise_Linux-9-Configuring_and_managing_networking-en-US.pdf:ro,z', '-v', '/home/till/RamaLama_rag_j3ndvtft/vectordb:/output:z', '--device', 'nvidia.com/gpu=all', '-e', 'CUDA_VISIBLE_DEVICES=0', 'quay.io/ramalama/cuda-rag:0.7', 'doc2rag', '/output', '/docs/']' returned non-zero exit status 137.

The final error is also only shown after hitting the enter key. So it first seems that something happens for a long time while it actually just seems to be waiting for input.

### Describe the results you expected

Successfully built rag. It worked with this file: https://github.com/nmstate/nmstate.github.io/blob/main/examples.md

### ramalama info output

```yaml
{
    "Accelerator": "cuda",
    "Engine": {
        "Info": {
            "host": {
                "arch": "amd64",
                "buildahVersion": "1.39.4",
                "cgroupControllers": [
                    "cpu",
                    "io",
                    "memory",
                    "pids"
                ],
                "cgroupManager": "systemd",
                "cgroupVersion": "v2",
                "conmon": {
                    "package": "conmon-2.1.13-1.fc42.x86_64",
                    "path": "/usr/bin/conmon",
                    "version": "conmon version 2.1.13, commit: "
                },
                "cpuUtilization": {
                    "idlePercent": 99.43,
                    "systemPercent": 0.23,
                    "userPercent": 0.34
                },
                "cpus": 24,
                "databaseBackend": "sqlite",
                "distribution": {
                    "distribution": "fedora",
                    "variant": "workstation",
                    "version": "42"
                },
                "eventLogger": "journald",
                "freeLocks": 2042,
                "hostname": "genius",
                "idMappings": {
                    "gidmap": [
                        {
                            "container_id": 0,
                            "host_id": 1000,
                            "size": 1
                        },
                        {
                            "container_id": 1,
                            "host_id": 524288,
                            "size": 65536
                        }
                    ],
                    "uidmap": [
                        {
                            "container_id": 0,
                            "host_id": 1000,
                            "size": 1
                        },
                        {
                            "container_id": 1,
                            "host_id": 524288,
                            "size": 65536
                        }
                    ]
                },
                "kernel": "6.14.2-300.fc42.x86_64",
                "linkmode": "dynamic",
                "logDriver": "journald",
                "memFree": 131237969920,
                "memTotal": 134821318656,
                "networkBackend": "netavark",
                "networkBackendInfo": {
                    "backend": "netavark",
                    "dns": {
                        "package": "aardvark-dns-1.14.0-1.fc42.x86_64",
                        "path": "/usr/libexec/podman/aardvark-dns",
                        "version": "aardvark-dns 1.14.0"
                    },
                    "package": "netavark-1.14.1-1.fc42.x86_64",
                    "path": "/usr/libexec/podman/netavark",
                    "version": "netavark 1.14.1"
                },
                "ociRuntime": {
                    "name": "crun",
                    "package": "crun-1.21-1.fc42.x86_64",
                    "path": "/usr/bin/crun",
                    "version": "crun version 1.21\ncommit: 10269840aa07fb7e6b7e1acff6198692d8ff5c88\nrundir: /run/user/1000/crun\nspec: 1.0.0\n+SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +LIBKRUN +WASM:wasmedge +YAJL"
                },
                "os": "linux",
                "pasta": {
                    "executable": "/usr/bin/pasta",
                    "package": "passt-0^20250320.g32f6212-2.fc42.x86_64",
                    "version": ""
                },
                "remoteSocket": {
                    "exists": true,
                    "path": "/run/user/1000/podman/podman.sock"
                },
                "rootlessNetworkCmd": "pasta",
                "security": {
                    "apparmorEnabled": false,
                    "capabilities": "CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT",
                    "rootless": true,
                    "seccompEnabled": true,
                    "seccompProfilePath": "/usr/share/containers/seccomp.json",
                    "selinuxEnabled": true
                },
                "serviceIsRemote": false,
                "slirp4netns": {
                    "executable": "/usr/bin/slirp4netns",
                    "package": "slirp4netns-1.3.1-2.fc42.x86_64",
                    "version": "slirp4netns version 1.3.1\ncommit: e5e368c4f5db6ae75c2fce786e31eef9da6bf236\nlibslirp: 4.8.0\nSLIRP_CONFIG_VERSION_MAX: 5\nlibseccomp: 2.5.5"
                },
                "swapFree": 6406365184,
                "swapTotal": 8589930496,
                "uptime": "25h 57m 0.00s (Approximately 1.04 days)",
                "variant": ""
            },
            "plugins": {
                "authorization": null,
                "log": [
                    "k8s-file",
                    "none",
                    "passthrough",
                    "journald"
                ],
                "network": [
                    "bridge",
                    "macvlan",
                    "ipvlan"
                ],
                "volume": [
                    "local"
                ]
            },
            "registries": {
                "search": [
                    "registry.fedoraproject.org",
                    "registry.access.redhat.com",
                    "docker.io"
                ]
            },
            "store": {
                "configFile": "/home/till/.config/containers/storage.conf",
                "containerStore": {
                    "number": 5,
                    "paused": 0,
                    "running": 0,
                    "stopped": 5
                },
                "graphDriverName": "overlay",
                "graphOptions": {},
                "graphRoot": "/home/till/.local/share/containers/storage",
                "graphRootAllocated": 536608768000,
                "graphRootUsed": 149010317312,
                "graphStatus": {
                    "Backing Filesystem": "xfs",
                    "Native Overlay Diff": "true",
                    "Supports d_type": "true",
                    "Supports shifting": "false",
                    "Supports volatile": "true",
                    "Using metacopy": "false"
                },
                "imageCopyTmpDir": "/var/tmp",
                "imageStore": {
                    "number": 28
                },
                "runRoot": "/run/user/1000/containers",
                "transientStore": false,
                "volumePath": "/home/till/.local/share/containers/storage/volumes"
            },
            "version": {
                "APIVersion": "5.4.2",
                "BuildOrigin": "Fedora Project",
                "Built": 1743552000,
                "BuiltTime": "Wed Apr  2 02:00:00 2025",
                "GitCommit": "be85287fcf4590961614ee37be65eeb315e5d9ff",
                "GoVersion": "go1.24.1",
                "Os": "linux",
                "OsArch": "linux/amd64",
                "Version": "5.4.2"
            }
        },
        "Name": "podman"
    },
    "Image": "quay.io/ramalama/cuda:0.7",
    "Runtime": "llama.cpp",
    "Store": "/home/till/.local/share/ramalama",
    "UseContainer": true,
    "Version": "0.7.4"
}
```

### Upstream Latest Release

No

### Additional environment details

Additional environment details

### Additional information

Run with debug output:

```
$ ramalama --debug rag Red_Hat_Enterprise_Linux-9-Configuring_and_managing_networking-en-US.pdf localhost/RHEL9networking-rag
run_cmd:  podman inspect quay.io/ramalama/cuda-rag:0.7
Working directory: None
Ignore stderr: False
Ignore all: True
Command finished with return code: 0
run_cmd:  podman run --rm -v /home/till/Red_Hat_Enterprise_Linux-9-Configuring_and_managing_networking-en-US.pdf:/docs//home/till/Red_Hat_Enterprise_Linux-9-Configuring_and_managing_networking-en-US.pdf:ro,z -v /home/till/RamaLama_rag_rcq_q9st/vectordb:/output:z --device nvidia.com/gpu=all -e CUDA_VISIBLE_DEVICES=0 quay.io/ramalama/cuda-rag:0.7 doc2rag /output /docs/
Working directory: None
Ignore stderr: False
Ignore all: False
Downloading detection model, please wait. This may take several minutes depending upon your network connection.
Downloading recognition model, please wait. This may take several minutes depending upon your network connection.
/usr/bin/doc2rag:46: DeprecationWarning: Use contextualize() instead.
  doc_text = chunker.serialize(chunk=chunk)
Error: Command '['podman', 'run', '--rm', '-v', '/home/till/Red_Hat_Enterprise_Linux-9-Configuring_and_managing_networking-en-US.pdf:/docs//home/till/Red_Hat_Enterprise_Linux-9-Configuring_and_managing_networking-en-US.pdf:ro,z', '-v', '/home/till/RamaLama_rag_rcq_q9st/vectordb:/output:z', '--device', 'nvidia.com/gpu=all', '-e', 'CUDA_VISIBLE_DEVICES=0', 'quay.io/ramalama/cuda-rag:0.7', 'doc2rag', '/output', '/docs/']' returned non-zero exit status 137.
```
