### ISSUE TITLE
Bad output from model served by ramalama

### ISSUE THREAD

**Issue by csutherl** [containers/ramalama#1289]
### Issue Description

I'm getting bad/weird output from the ramalama:latest image + mistral:latest model (and the granite-code:latest model too).  I'm using the following `ramalama --debug --image quay.io/ramalama/ramalama:latest serve --port 11434 mistral:latest` which starts up fine and hosts the web UI, but when prompting I get what appears to be nonsense repeating for quite a long while before stopping with mistral, and granite-code borks the output stream on the web UI and never prints anything (at least not while I had a very brief wait for it).

Thanks to the suggestion of @benoitf to use `--ngl 0` to force CPU inferencing I was able to get normal output from the models.

NOTE: I'm specifying the ramalama:latest image because I ran into #1251 with the intel-gpu image.

### Steps to reproduce the issue

To reproduce:

1. Serve  a model with ramalama: `ramalama --debug --image quay.io/ramalama/ramalama:latest serve --port 11434 mistral:latest`
2. Visit the web UI at `http://localhost:11434`
3. Prompt it with something like "What color is the sky?"
4. Observe random output when using mistral model, or weird UI issues if using granite-code

### Describe the results you received

Following the reproduction steps above, here is some example output:

```
Q: Hello! How are you?
A: mobilejaxDOM constitu whilst whilst AB mobileonical delightha whilst Trad whilstDroidridgeute constitusubscription AB organis sustoiDroid organis...
```

and

```
Q: What color is the sky?
A: Question Question Q Q Q Question Question User Question Question Q Q Q Q Question Question Q Q Q Question Q Q Question User User Q Q Question Question Q Q Q Q Q Q Question Question User Q Q Q Q Q Q Q User Question # Question Question Question Q Q Question Q Q Q Question Question # User Question Question // Q Q Q Question Question Q Question Question Q Question Q # Q User Q Q Q Q Q Q // # Q Question Question Question Q Q Question User Q Q User Q Q Q # User Q Question Q Question Question Q Q Question Q Q Q Question Q Question Question Q Question Question Q // Q Q User Q Q Question Q Question Question Question Question Question Question Q User Q Question Q Question Q Question Question Q /******/ Q Q # Q Question
```

with the output strings repeating until I killed it for several minutes.

### Describe the results you expected

Actual responses rather than seemingly random words/letters.

### ramalama info output

```yaml
{
    "Accelerator": "intel",
    "Engine": {
        "Info": {
            "host": {
                "arch": "amd64",
                "buildahVersion": "1.39.4",
                "cgroupControllers": [
                    "cpu",
                    "io",
                    "memory",
                    "pids"
                ],
                "cgroupManager": "systemd",
                "cgroupVersion": "v2",
                "conmon": {
                    "package": "conmon-2.1.13-1.fc42.x86_64",
                    "path": "/usr/bin/conmon",
                    "version": "conmon version 2.1.13, commit: "
                },
                "cpuUtilization": {
                    "idlePercent": 98.16,
                    "systemPercent": 0.4,
                    "userPercent": 1.45
                },
                "cpus": 22,
                "databaseBackend": "sqlite",
                "distribution": {
                    "distribution": "fedora",
                    "variant": "workstation",
                    "version": "42"
                },
                "eventLogger": "journald",
                "freeLocks": 2044,
                "hostname": "my-fedora42",
                "idMappings": {
                    "gidmap": [
                        {
                            "container_id": 0,
                            "host_id": 17833,
                            "size": 1
                        },
                        {
                            "container_id": 1,
                            "host_id": 165536,
                            "size": 165536
                        }
                    ],
                    "uidmap": [
                        {
                            "container_id": 0,
                            "host_id": 17833,
                            "size": 1
                        },
                        {
                            "container_id": 1,
                            "host_id": 165536,
                            "size": 165536
                        }
                    ]
                },
                "kernel": "6.14.2-300.fc42.x86_64",
                "linkmode": "dynamic",
                "logDriver": "journald",
                "memFree": 15207501824,
                "memTotal": 66819031040,
                "networkBackend": "netavark",
                "networkBackendInfo": {
                    "backend": "netavark",
                    "dns": {
                        "package": "aardvark-dns-1.14.0-1.fc42.x86_64",
                        "path": "/usr/libexec/podman/aardvark-dns",
                        "version": "aardvark-dns 1.14.0"
                    },
                    "package": "netavark-1.14.1-1.fc42.x86_64",
                    "path": "/usr/libexec/podman/netavark",
                    "version": "netavark 1.14.1"
                },
                "ociRuntime": {
                    "name": "crun",
                    "package": "crun-1.21-1.fc42.x86_64",
                    "path": "/usr/bin/crun",
                    "version": "crun version 1.21\ncommit: 10269840aa07fb7e6b7e1acff6198692d8ff5c88\nrundir: /run/user/17833/crun\nspec: 1.0.0\n+SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +LIBKRUN +WASM:wasmedge +YAJL"
                },
                "os": "linux",
                "pasta": {
                    "executable": "/usr/bin/pasta",
                    "package": "passt-0^20250320.g32f6212-2.fc42.x86_64",
                    "version": ""
                },
                "remoteSocket": {
                    "exists": true,
                    "path": "/run/user/17833/podman/podman.sock"
                },
                "rootlessNetworkCmd": "pasta",
                "security": {
                    "apparmorEnabled": false,
                    "capabilities": "CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT",
                    "rootless": true,
                    "seccompEnabled": true,
                    "seccompProfilePath": "/usr/share/containers/seccomp.json",
                    "selinuxEnabled": true
                },
                "serviceIsRemote": false,
                "slirp4netns": {
                    "executable": "",
                    "package": "",
                    "version": ""
                },
                "swapFree": 8588636160,
                "swapTotal": 8589930496,
                "uptime": "196h 9m 45.00s (Approximately 8.17 days)",
                "variant": ""
            },
            "plugins": {
                "authorization": null,
                "log": [
                    "k8s-file",
                    "none",
                    "passthrough",
                    "journald"
                ],
                "network": [
                    "bridge",
                    "macvlan",
                    "ipvlan"
                ],
                "volume": [
                    "local"
                ]
            },
            "registries": {
                "search": [
                    "registry.fedoraproject.org",
                    "registry.access.redhat.com",
                    "docker.io"
                ]
            },
            "store": {
                "configFile": "/home/me/.config/containers/storage.conf",
                "containerStore": {
                    "number": 4,
                    "paused": 0,
                    "running": 0,
                    "stopped": 4
                },
                "graphDriverName": "overlay",
                "graphOptions": {},
                "graphRoot": "/home/me/.local/share/containers/storage",
                "graphRootAllocated": 1022488809472,
                "graphRootUsed": 46517395456,
                "graphStatus": {
                    "Backing Filesystem": "btrfs",
                    "Native Overlay Diff": "true",
                    "Supports d_type": "true",
                    "Supports shifting": "false",
                    "Supports volatile": "true",
                    "Using metacopy": "false"
                },
                "imageCopyTmpDir": "/var/tmp",
                "imageStore": {
                    "number": 2
                },
                "runRoot": "/run/user/17833/containers",
                "transientStore": false,
                "volumePath": "/home/me/.local/share/containers/storage/volumes"
            },
            "version": {
                "APIVersion": "5.4.2",
                "BuildOrigin": "Fedora Project",
                "Built": 1743552000,
                "BuiltTime": "Tue Apr  1 20:00:00 2025",
                "GitCommit": "be85287fcf4590961614ee37be65eeb315e5d9ff",
                "GoVersion": "go1.24.1",
                "Os": "linux",
                "OsArch": "linux/amd64",
                "Version": "5.4.2"
            }
        },
        "Name": "podman"
    },
    "Image": "quay.io/ramalama/ramalama",
    "Runtime": "llama.cpp",
    "Store": "/home/me/.local/share/ramalama",
    "UseContainer": true,
    "Version": "0.7.2"
}
```

### Upstream Latest Release

Yes
