### ISSUE TITLE
Look like it should be the version of tool ramalama itself, not AI Model

### ISSUE THREAD

**Issue by guoguojenna** [containers/ramalama#1297]
### Issue Description

Actual output:
```
$ ramalama -h | grep 'version             display version of AI Model'
    version             display version of AI Model
```
Expect:
```
$ ramalama -h | grep 'version            '
    version             display version of ramalama
```

### Steps to reproduce the issue

```
$ ramalama -h | grep 'version             display version of AI Model'
    version             display version of AI Model
```

### Describe the results you received

```
$ ramalama -h | grep 'version             display version of AI Model'
    version             display version of AI Model
```

### Describe the results you expected

```
$ ramalama -h | grep 'version             '
    version             display version of ramalama
```

### ramalama info output

```yaml
$ ramalama info
{
    "Accelerator": "none",
    "Engine": {
        "Info": {
            "host": {
                "arch": "amd64",
                "buildahVersion": "1.38.0",
                "cgroupControllers": [
                    "cpu",
                    "memory",
                    "pids"
                ],
                "cgroupManager": "systemd",
                "cgroupVersion": "v2",
                "conmon": {
                    "package": "conmon-2.1.12-3.fc41.x86_64",
                    "path": "/usr/bin/conmon",
                    "version": "conmon version 2.1.12, commit: "
                },
                "cpuUtilization": {
                    "idlePercent": 96.93,
                    "systemPercent": 1.4,
                    "userPercent": 1.67
                },
                "cpus": 4,
                "databaseBackend": "sqlite",
                "distribution": {
                    "distribution": "fedora",
                    "variant": "cloud",
                    "version": "41"
                },
                "eventLogger": "journald",
                "freeLocks": 2047,
                "hostname": "yizhan-image-mode",
                "idMappings": {
                    "gidmap": [
                        {
                            "container_id": 0,
                            "host_id": 1002,
                            "size": 1
                        },
                        {
                            "container_id": 1,
                            "host_id": 655360,
                            "size": 65536
                        }
                    ],
                    "uidmap": [
                        {
                            "container_id": 0,
                            "host_id": 1002,
                            "size": 1
                        },
                        {
                            "container_id": 1,
                            "host_id": 655360,
                            "size": 65536
                        }
                    ]
                },
                "kernel": "6.11.4-301.fc41.x86_64",
                "linkmode": "dynamic",
                "logDriver": "journald",
                "memFree": 990515200,
                "memTotal": 8316452864,
                "networkBackend": "netavark",
                "networkBackendInfo": {
                    "backend": "netavark",
                    "dns": {
                        "package": "aardvark-dns-1.12.2-2.fc41.x86_64",
                        "path": "/usr/libexec/podman/aardvark-dns",
                        "version": "aardvark-dns 1.12.2"
                    },
                    "package": "netavark-1.12.2-1.fc41.x86_64",
                    "path": "/usr/libexec/podman/netavark",
                    "version": "netavark 1.12.2"
                },
                "ociRuntime": {
                    "name": "crun",
                    "package": "crun-1.17-1.fc41.x86_64",
                    "path": "/usr/bin/crun",
                    "version": "crun version 1.17\ncommit: 000fa0d4eeed8938301f3bcf8206405315bc1017\nrundir: /run/user/1002/crun\nspec: 1.0.0\n+SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +LIBKRUN +WASM:wasmedge +YAJL"
                },
                "os": "linux",
                "pasta": {
                    "executable": "/usr/bin/pasta",
                    "package": "passt-0^20240906.g6b38f07-1.fc41.x86_64",
                    "version": "pasta 0^20240906.g6b38f07-1.fc41.x86_64\nCopyright Red Hat\nGNU General Public License, version 2 or later\n  <https://www.gnu.org/licenses/old-licenses/gpl-2.0.html>\nThis is free software: you are free to change and redistribute it.\nThere is NO WARRANTY, to the extent permitted by law.\n"
                },
                "remoteSocket": {
                    "exists": true,
                    "path": "/run/user/1002/podman/podman.sock"
                },
                "rootlessNetworkCmd": "pasta",
                "security": {
                    "apparmorEnabled": false,
                    "capabilities": "CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT",
                    "rootless": true,
                    "seccompEnabled": true,
                    "seccompProfilePath": "/usr/share/containers/seccomp.json",
                    "selinuxEnabled": true
                },
                "serviceIsRemote": false,
                "slirp4netns": {
                    "executable": "",
                    "package": "",
                    "version": ""
                },
                "swapFree": 7484993536,
                "swapTotal": 8316252160,
                "uptime": "3305h 28m 11.00s (Approximately 137.71 days)",
                "variant": ""
            },
            "plugins": {
                "authorization": null,
                "log": [
                    "k8s-file",
                    "none",
                    "passthrough",
                    "journald"
                ],
                "network": [
                    "bridge",
                    "macvlan",
                    "ipvlan"
                ],
                "volume": [
                    "local"
                ]
            },
            "registries": {
                "search": [
                    "registry.fedoraproject.org",
                    "registry.access.redhat.com",
                    "docker.io"
                ]
            },
            "store": {
                "configFile": "/home/zguo/.config/containers/storage.conf",
                "containerStore": {
                    "number": 1,
                    "paused": 0,
                    "running": 1,
                    "stopped": 0
                },
                "graphDriverName": "overlay",
                "graphOptions": {},
                "graphRoot": "/home/zguo/.local/share/containers/storage",
                "graphRootAllocated": 63267909632,
                "graphRootUsed": 25416507392,
                "graphStatus": {
                    "Backing Filesystem": "btrfs",
                    "Native Overlay Diff": "true",
                    "Supports d_type": "true",
                    "Supports shifting": "false",
                    "Supports volatile": "true",
                    "Using metacopy": "false"
                },
                "imageCopyTmpDir": "/var/tmp",
                "imageStore": {
                    "number": 30
                },
                "runRoot": "/run/user/1002/containers",
                "transientStore": false,
                "volumePath": "/home/zguo/.local/share/containers/storage/volumes"
            },
            "version": {
                "APIVersion": "5.3.1",
                "Built": 1732147200,
                "BuiltTime": "Thu Nov 21 00:00:00 2024",
                "GitCommit": "",
                "GoVersion": "go1.23.3",
                "Os": "linux",
                "OsArch": "linux/amd64",
                "Version": "5.3.1"
            }
        },
        "Name": "podman"
    },
    "Image": "quay.io/ramalama/ramalama:0.7",
    "Runtime": "llama.cpp",
    "Store": "/home/zguo/.local/share/ramalama",
    "UseContainer": true,
    "Version": "0.7.5"
}
```

### Upstream Latest Release

Yes
