### ISSUE TITLE
Error: pop from empty list

### ISSUE THREAD

**Issue by guoguojenna** [containers/ramalama#1304]
### Issue Description

Show 'Error: pop from empty list' when run a mode the first time.

✗ ramalama run llama3.2 
 99% |██████████████████████████████████████████ |    1.88 GB/   1.88 GB   7.68 MB/s        0sError: pop from empty list

### Steps to reproduce the issue

Run a model that you have not pulled before.

✗ ramalama run llama3.2 
 99% |██████████████████████████████████████████ |    1.88 GB/   1.88 GB   7.68 MB/s        0sError: pop from empty list

### Describe the results you received

Error: pop from empty list

### Describe the results you expected

No error 'Error: pop from empty list'

### ramalama info output

```yaml
✗ ramalama info
{
    "Accelerator": "none",
    "Engine": {
        "Info": {
            "host": {
                "arch": "amd64",
                "buildahVersion": "1.31.2",
                "cgroupControllers": [
                    "cpu",
                    "io",
                    "memory",
                    "pids"
                ],
                "cgroupManager": "systemd",
                "cgroupVersion": "v2",
                "conmon": {
                    "package": "conmon-2.1.7-2.fc37.x86_64",
                    "path": "/usr/bin/conmon",
                    "version": "conmon version 2.1.7, commit: "
                },
                "cpuUtilization": {
                    "idlePercent": 98.28,
                    "systemPercent": 0.43,
                    "userPercent": 1.29
                },
                "cpus": 8,
                "databaseBackend": "boltdb",
                "distribution": {
                    "distribution": "fedora",
                    "variant": "workstation",
                    "version": "37"
                },
                "eventLogger": "journald",
                "freeLocks": 2048,
                "hostname": "fedora",
                "idMappings": {
                    "gidmap": [
                        {
                            "container_id": 0,
                            "host_id": 1000,
                            "size": 1
                        },
                        {
                            "container_id": 1,
                            "host_id": 100000,
                            "size": 65536
                        }
                    ],
                    "uidmap": [
                        {
                            "container_id": 0,
                            "host_id": 1000,
                            "size": 1
                        },
                        {
                            "container_id": 1,
                            "host_id": 100000,
                            "size": 65536
                        }
                    ]
                },
                "kernel": "6.4.12-100.fc37.x86_64",
                "linkmode": "dynamic",
                "logDriver": "journald",
                "memFree": 2187198464,
                "memTotal": 33331286016,
                "networkBackend": "netavark",
                "networkBackendInfo": {
                    "backend": "netavark",
                    "dns": {
                        "package": "aardvark-dns-1.7.0-1.fc37.x86_64",
                        "path": "/usr/libexec/podman/aardvark-dns",
                        "version": "aardvark-dns 1.7.0"
                    },
                    "package": "netavark-1.7.0-1.fc37.x86_64",
                    "path": "/usr/libexec/podman/netavark",
                    "version": "netavark 1.7.0"
                },
                "ociRuntime": {
                    "name": "crun",
                    "package": "crun-1.8.6-1.fc37.x86_64",
                    "path": "/usr/bin/crun",
                    "version": "crun version 1.8.6\ncommit: 73f759f4a39769f60990e7d225f561b4f4f06bcf\nrundir: /run/user/1000/crun\nspec: 1.0.0\n+SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +LIBKRUN +WASM:wasmedge +YAJL"
                },
                "os": "linux",
                "pasta": {
                    "executable": "/usr/bin/pasta",
                    "package": "passt-0^20230625.g32660ce-1.fc37.x86_64",
                    "version": "pasta 0^20230625.g32660ce-1.fc37.x86_64\nCopyright Red Hat\nGNU Affero GPL version 3 or later <https://www.gnu.org/licenses/agpl-3.0.html>\nThis is free software: you are free to change and redistribute it.\nThere is NO WARRANTY, to the extent permitted by law.\n"
                },
                "remoteSocket": {
                    "path": "/run/user/1000/podman/podman.sock"
                },
                "security": {
                    "apparmorEnabled": false,
                    "capabilities": "CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT",
                    "rootless": true,
                    "seccompEnabled": true,
                    "seccompProfilePath": "/usr/share/containers/seccomp.json",
                    "selinuxEnabled": true
                },
                "serviceIsRemote": false,
                "slirp4netns": {
                    "executable": "/usr/bin/slirp4netns",
                    "package": "slirp4netns-1.2.0-8.fc37.x86_64",
                    "version": "slirp4netns version 1.2.0\ncommit: 656041d45cfca7a4176f6b7eed9e4fe6c11e8383\nlibslirp: 4.7.0\nSLIRP_CONFIG_VERSION_MAX: 4\nlibseccomp: 2.5.3"
                },
                "swapFree": 8589930496,
                "swapTotal": 8589930496,
                "uptime": "23h 21m 54.00s (Approximately 0.96 days)"
            },
            "plugins": {
                "authorization": null,
                "log": [
                    "k8s-file",
                    "none",
                    "passthrough",
                    "journald"
                ],
                "network": [
                    "bridge",
                    "macvlan",
                    "ipvlan"
                ],
                "volume": [
                    "local"
                ]
            },
            "registries": {
                "search": [
                    "registry.fedoraproject.org",
                    "registry.access.redhat.com",
                    "docker.io",
                    "quay.io"
                ]
            },
            "store": {
                "configFile": "/home/zguo/.config/containers/storage.conf",
                "containerStore": {
                    "number": 0,
                    "paused": 0,
                    "running": 0,
                    "stopped": 0
                },
                "graphDriverName": "overlay",
                "graphOptions": {},
                "graphRoot": "/home/zguo/.local/share/containers/storage",
                "graphRootAllocated": 501657608192,
                "graphRootUsed": 118163988480,
                "graphStatus": {
                    "Backing Filesystem": "extfs",
                    "Native Overlay Diff": "true",
                    "Supports d_type": "true",
                    "Using metacopy": "false"
                },
                "imageCopyTmpDir": "/var/tmp",
                "imageStore": {
                    "number": 19
                },
                "runRoot": "/run/user/1000/containers",
                "transientStore": false,
                "volumePath": "/home/zguo/.local/share/containers/storage/volumes"
            },
            "version": {
                "APIVersion": "4.6.1",
                "Built": 1691705275,
                "BuiltTime": "Fri Aug 11 06:07:55 2023",
                "GitCommit": "",
                "GoVersion": "go1.19.10",
                "Os": "linux",
                "OsArch": "linux/amd64",
                "Version": "4.6.1"
            }
        },
        "Name": "podman"
    },
    "Image": "quay.io/ramalama/ramalama:0.7",
    "Runtime": "llama.cpp",
    "Store": "/home/zguo/.local/share/ramalama",
    "UseContainer": true,
    "Version": "0.7.5"
}
```

### Upstream Latest Release

Yes
