### ISSUE TITLE
llama server fails to find Intel GPU and crashes

### ISSUE THREAD

**Issue by qmarcou** [containers/ramalama#1585]
### Issue Description

I'd like to use my intel iGPU ([my CPU](https://www.intel.com/content/www/us/en/products/sku/236851/intel-core-ultra-7-processor-165h-24m-cache-up-to-5-00-ghz/specifications.html)  is bundled with an iGPU ID ID55 Intel Arc MeteorLake which is listed on [ramalama's compatibility table](https://github.com/containers/ramalama?tab=readme-ov-file#intel-gpus))   to run local chats,  on an ubuntu 24.04 system with podman installed. 

I however fail to serve/run any model, the container crashes upon start and doesn't even get listed in `podman ps --all` afterward. When using `ramalama run amodel` the terminal hangs until I enter any command and then fails with error `Error: could not connect to: http://127.0.0.1:8080/v1/chat/completions` not matter how long I wait before entering an input. After reading #1568 I've tried `ramalama serve amodel` instead and get 
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  can not find preferred GPU platform
```

Any pointers on how to debug?
Thanks for the help!

### Steps to reproduce the issue

```sh
> pipx install ramalama
> ramalama pull tinyllama
> ramalama serve tinyllama
```

### Describe the results you received

This fails with the following output:
```sh
:: initializing oneAPI environment ...
   entrypoint.sh: BASH_VERSION = 5.2.37(1)-release
   args: Using "$@" for setvars.sh arguments: /usr/libexec/ramalama/ramalama-serve-core llama-server --port 8080 --model /mnt/models/model.file --no-warmup --jinja --log-colors --alias tinyllama --ctx-size 2048 --temp 0.8 --cache-reuse 256 -ngl 999 --threads 11 --host 0.0.0.0
:: compiler -- latest
:: mkl -- latest
:: tbb -- latest
:: umf -- latest
:: oneAPI environment initialized ::
 
/lib64/libggml-base.so(+0x26d8) [0x76b7a9b3f6d8]
/lib64/libggml-base.so(ggml_print_backtrace+0x285) [0x76b7a9b3f6b5]
/lib64/libggml-base.so(+0x17486) [0x76b7a9b54486]
/lib64/libstdc++.so.6(+0x1eadc) [0x76b7a98e4adc]
/lib64/libstdc++.so.6(_ZSt10unexpectedv+0x0) [0x76b7a98ced3c]
/lib64/libstdc++.so.6(+0x1ed88) [0x76b7a98e4d88]
/lib64/libggml-sycl.so(_ZN4dpct7dev_mgrC2Ev+0x2067) [0x76b7a9c620d7]
/lib64/libggml-sycl.so(+0x3190) [0x76b7a9c35190]
/lib64/libggml-sycl.so(ggml_backend_sycl_reg+0xbc) [0x76b7a9c3779c]
/lib64/libggml.so(_ZN21ggml_backend_registryC2Ev+0x1d) [0x76b7aa0def0d]
/lib64/libggml.so(ggml_backend_reg_by_name+0x123) [0x76b7aa0dbc03]
/lib64/libllama.so(llama_supports_rpc+0xd) [0x76b7aa0f5acd]
llama-server() [0x4ee456]
llama-server() [0x4bfee2]
llama-server() [0x406506]
/lib64/libc.so.6(+0x35f5) [0x76b7a95bb5f5]
/lib64/libc.so.6(__libc_start_main+0x88) [0x76b7a95bb6a8]
llama-server() [0x4063e5]
terminate called after throwing an instance of 'std::runtime_error'
  what():  can not find preferred GPU platform
```

It seems that ramalama has downlaoded the correct image for my config:
```sh
> podman images
REPOSITORY                  TAG         IMAGE ID      CREATED     SIZE
quay.io/ramalama/intel-gpu  0.9         eac7acb20df9  6 days ago  3.3 GB

```

Using `--dryrun` to get the podman command I get:
```sh
> ramalama --dry-run serve tinyllama
podman run --rm --label ai.ramalama.model=tinyllama --label ai.ramalama.engine=podman --label ai.ramalama.runtime=llama.cpp --label ai.ramalama.port=8082 --label ai.ramalama.command=serve --device /dev/dri --device /dev/accel -e INTEL_VISIBLE_DEVICES=1 -p 8082:8082 --security-opt=label=disable --cap-drop=all --security-opt=no-new-privileges --pull newer --label ai.ramalama --name ramalama_k9gI9kV2vt --env=HOME=/tmp --init --mount=type=bind,src=/home/charles/.local/share/ramalama/store/ollama/tinyllama/tinyllama/blobs/sha256-2af3b81862c6be03c769683af18efdadb2c33f60ff32ab6f83e42c043d6c7816,destination=/mnt/models/model.file,ro --mount=type=bind,src=/home/charles/.local/share/ramalama/store/ollama/tinyllama/tinyllama/snapshots/sha256-2af3b81862c6be03c769683af18efdadb2c33f60ff32ab6f83e42c043d6c7816/chat_template_converted,destination=/mnt/models/chat_template.file,ro quay.io/ramalama/intel-gpu:0.9 /usr/libexec/ramalama/ramalama-serve-core llama-server --port 8082 --model /mnt/models/model.file --no-warmup --jinja --log-colors --alias tinyllama --ctx-size 2048 --temp 0.8 --cache-reuse 256 -ngl 999 --threads 11 --host 0.0.0.0
```
I've tried to create a container without the llama-server launch command:
```sh
> podman run --rm --label ai.ramalama.model=tinyllama --label ai.ramalama.engine=podman --label ai.ramalama.runtime=llama.cpp --label ai.ramalama.port=8082 --label ai.ramalama.command=serve --device /dev/dri --device /dev/accel -e INTEL_VISIBLE_DEVICES=1 -p 8082:8082 --security-opt=label=disable --cap-drop=all --security-opt=no-new-privileges --pull newer --label ai.ramalama --name ramalama_k9gI9kV2vt --env=HOME=/tmp --init --mount=type=bind,src=/home/charles/.local/share/ramalama/store/ollama/tinyllama/tinyllama/blobs/sha256-2af3b81862c6be03c769683af18efdadb2c33f60ff32ab6f83e42c043d6c7816,destination=/mnt/models/model.file,ro --mount=type=bind,src=/home/charles/.local/share/ramalama/store/ollama/tinyllama/tinyllama/snapshots/sha256-2af3b81862c6be03c769683af18efdadb2c33f60ff32ab6f83e42c043d6c7816/chat_template_converted,destination=/mnt/models/chat_template.file,ro quay.io/ramalama/intel-gpu:0.9
```
that gets created without error. The GPU devices seem to be correctly passed to the container:
```sh
> podman ps
CONTAINER ID  IMAGE                           COMMAND            CREATED         STATUS         PORTS                   NAMES
253b82f7917c  quay.io/ramalama/intel-gpu:0.9  tail -f /dev/null  13 seconds ago  Up 14 seconds  0.0.0.0:8080->8080/tcp  ramalama_k9gI9kV2vt

> podman exec ramalama_k9gI9kV2vt ls -la /dev/dri/
total 0
drwxr-xr-x  2 root   root         80 Jun 23 12:11 .
drwxr-xr-x  7 root   root        380 Jun 23 12:11 ..
crw-rw----+ 1 nobody nobody 226,   1 Jun 23 11:39 card1
crw-rw----+ 1 nobody nobody 226, 128 Jun 23 11:39 renderD128
``` 

### Describe the results you expected

Well, something that finds my iGPU doesn't crash :)
And if doesn't find my GPU, I would expect it to still run onto CPU without crashing but issuing a warning.

### ramalama info output

```yaml
ramalama info
{
    "Accelerator": "intel",
    "Engine": {
        "Info": {
            "host": {
                "arch": "amd64",
                "buildahVersion": "1.33.7",
                "cgroupControllers": [
                    "memory",
                    "pids"
                ],
                "cgroupManager": "systemd",
                "cgroupVersion": "v2",
                "conmon": {
                    "package": "conmon_2.1.10+ds1-1build2_amd64",
                    "path": "/usr/bin/conmon",
                    "version": "conmon version 2.1.10, commit: unknown"
                },
                "cpuUtilization": {
                    "idlePercent": 99.55,
                    "systemPercent": 0.13,
                    "userPercent": 0.31
                },
                "cpus": 22,
                "databaseBackend": "sqlite",
                "distribution": {
                    "codename": "noble",
                    "distribution": "ubuntu",
                    "version": "24.04"
                },
                "eventLogger": "journald",
                "freeLocks": 2047,
                "hostname": "thor",
                "idMappings": {
                    "gidmap": [
                        {
                            "container_id": 0,
                            "host_id": 1000,
                            "size": 1
                        },
                        {
                            "container_id": 1,
                            "host_id": 100000,
                            "size": 65536
                        }
                    ],
                    "uidmap": [
                        {
                            "container_id": 0,
                            "host_id": 1000,
                            "size": 1
                        },
                        {
                            "container_id": 1,
                            "host_id": 100000,
                            "size": 65536
                        }
                    ]
                },
                "kernel": "6.11.0-26-generic",
                "linkmode": "dynamic",
                "logDriver": "journald",
                "memFree": 57842454528,
                "memTotal": 66820259840,
                "networkBackend": "netavark",
                "networkBackendInfo": {
                    "backend": "netavark",
                    "dns": {
                        "package": "aardvark-dns_1.4.0-5_amd64",
                        "path": "/usr/lib/podman/aardvark-dns",
                        "version": "aardvark-dns 1.4.0"
                    },
                    "package": "netavark_1.4.0-4_amd64",
                    "path": "/usr/lib/podman/netavark",
                    "version": "netavark 1.4.0"
                },
                "ociRuntime": {
                    "name": "crun",
                    "package": "crun_1.14.1-1_amd64",
                    "path": "/usr/bin/crun",
                    "version": "crun version 1.14.1\ncommit: de537a7965bfbe9992e2cfae0baeb56a08128171\nrundir: /run/user/1000/crun\nspec: 1.0.0\n+SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +WASM:wasmedge +YAJL"
                },
                "os": "linux",
                "pasta": {
                    "executable": "/usr/bin/pasta",
                    "package": "passt_0.0~git20240220.1e6f92b-1_amd64",
                    "version": "pasta unknown version\nCopyright Red Hat\nGNU General Public License, version 2 or later\n  <https://www.gnu.org/licenses/old-licenses/gpl-2.0.html>\nThis is free software: you are free to change and redistribute it.\nThere is NO WARRANTY, to the extent permitted by law.\n"
                },
                "remoteSocket": {
                    "exists": false,
                    "path": "/run/user/1000/podman/podman.sock"
                },
                "security": {
                    "apparmorEnabled": false,
                    "capabilities": "CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT",
                    "rootless": true,
                    "seccompEnabled": true,
                    "seccompProfilePath": "/usr/share/containers/seccomp.json",
                    "selinuxEnabled": false
                },
                "serviceIsRemote": false,
                "slirp4netns": {
                    "executable": "/usr/bin/slirp4netns",
                    "package": "slirp4netns_1.2.1-1build2_amd64",
                    "version": "slirp4netns version 1.2.1\ncommit: 09e31e92fa3d2a1d3ca261adaeb012c8d75a8194\nlibslirp: 4.7.0\nSLIRP_CONFIG_VERSION_MAX: 4\nlibseccomp: 2.5.5"
                },
                "swapFree": 8589930496,
                "swapTotal": 8589930496,
                "uptime": "2h 22m 30.00s (Approximately 0.08 days)",
                "variant": ""
            },
            "plugins": {
                "authorization": null,
                "log": [
                    "k8s-file",
                    "none",
                    "passthrough",
                    "journald"
                ],
                "network": [
                    "bridge",
                    "macvlan",
                    "ipvlan"
                ],
                "volume": [
                    "local"
                ]
            },
            "registries": {},
            "store": {
                "configFile": "/home/charles/.config/containers/storage.conf",
                "containerStore": {
                    "number": 1,
                    "paused": 0,
                    "running": 1,
                    "stopped": 0
                },
                "graphDriverName": "overlay",
                "graphOptions": {},
                "graphRoot": "/home/charles/.local/share/containers/storage",
                "graphRootAllocated": 854430220288,
                "graphRootUsed": 37641183232,
                "graphStatus": {
                    "Backing Filesystem": "extfs",
                    "Native Overlay Diff": "true",
                    "Supports d_type": "true",
                    "Supports shifting": "false",
                    "Supports volatile": "true",
                    "Using metacopy": "false"
                },
                "imageCopyTmpDir": "/var/tmp",
                "imageStore": {
                    "number": 1
                },
                "runRoot": "/run/user/1000/containers",
                "transientStore": false,
                "volumePath": "/home/charles/.local/share/containers/storage/volumes"
            },
            "version": {
                "APIVersion": "4.9.3",
                "Built": 0,
                "BuiltTime": "Thu Jan  1 01:00:00 1970",
                "GitCommit": "",
                "GoVersion": "go1.22.2",
                "Os": "linux",
                "OsArch": "linux/amd64",
                "Version": "4.9.3"
            }
        },
        "Name": "podman"
    },
    "Image": "quay.io/ramalama/intel-gpu:0.9",
    "Runtime": "llama.cpp",
    "Shortnames": {
        "Files": [
            "/home/charles/.local/share/pipx/venvs/ramalama/share/ramalama/shortnames.conf"
        ],
        "Names": {
            "cerebrum": "huggingface://froggeric/Cerebrum-1.0-7b-GGUF/Cerebrum-1.0-7b-Q4_KS.gguf",
            "deepseek": "ollama://deepseek-r1",
            "dragon": "huggingface://llmware/dragon-mistral-7b-v0/dragon-mistral-7b-q4_k_m.gguf",
            "gemma3": "hf://ggml-org/gemma-3-4b-it-GGUF",
            "gemma3:12b": "hf://ggml-org/gemma-3-12b-it-GGUF",
            "gemma3:1b": "hf://ggml-org/gemma-3-1b-it-GGUF/gemma-3-1b-it-Q4_K_M.gguf",
            "gemma3:27b": "hf://ggml-org/gemma-3-27b-it-GGUF",
            "gemma3:4b": "hf://ggml-org/gemma-3-4b-it-GGUF",
            "granite": "ollama://granite3.1-dense",
            "granite-code": "hf://ibm-granite/granite-3b-code-base-2k-GGUF/granite-3b-code-base.Q4_K_M.gguf",
            "granite-code:20b": "hf://ibm-granite/granite-20b-code-base-8k-GGUF/granite-20b-code-base.Q4_K_M.gguf",
            "granite-code:34b": "hf://ibm-granite/granite-34b-code-base-8k-GGUF/granite-34b-code-base.Q4_K_M.gguf",
            "granite-code:3b": "hf://ibm-granite/granite-3b-code-base-2k-GGUF/granite-3b-code-base.Q4_K_M.gguf",
            "granite-code:8b": "hf://ibm-granite/granite-8b-code-base-4k-GGUF/granite-8b-code-base.Q4_K_M.gguf",
            "granite-lab-7b": "huggingface://instructlab/granite-7b-lab-GGUF/granite-7b-lab-Q4_K_M.gguf",
            "granite-lab-8b": "huggingface://ibm-granite/granite-8b-code-base-GGUF/granite-8b-code-base.Q4_K_M.gguf",
            "granite-lab:7b": "huggingface://instructlab/granite-7b-lab-GGUF/granite-7b-lab-Q4_K_M.gguf",
            "granite:2b": "ollama://granite3.1-dense:2b",
            "granite:7b": "huggingface://instructlab/granite-7b-lab-GGUF/granite-7b-lab-Q4_K_M.gguf",
            "granite:8b": "ollama://granite3.1-dense:8b",
            "hermes": "huggingface://NousResearch/Hermes-2-Pro-Mistral-7B-GGUF/Hermes-2-Pro-Mistral-7B.Q4_K_M.gguf",
            "ibm/granite": "ollama://granite3.1-dense:8b",
            "ibm/granite:2b": "ollama://granite3.1-dense:2b",
            "ibm/granite:7b": "huggingface://instructlab/granite-7b-lab-GGUF/granite-7b-lab-Q4_K_M.gguf",
            "ibm/granite:8b": "ollama://granite3.1-dense:8b",
            "merlinite": "huggingface://instructlab/merlinite-7b-lab-GGUF/merlinite-7b-lab-Q4_K_M.gguf",
            "merlinite-lab-7b": "huggingface://instructlab/merlinite-7b-lab-GGUF/merlinite-7b-lab-Q4_K_M.gguf",
            "merlinite-lab:7b": "huggingface://instructlab/merlinite-7b-lab-GGUF/merlinite-7b-lab-Q4_K_M.gguf",
            "merlinite:7b": "huggingface://instructlab/merlinite-7b-lab-GGUF/merlinite-7b-lab-Q4_K_M.gguf",
            "mistral": "huggingface://TheBloke/Mistral-7B-Instruct-v0.2-GGUF/mistral-7b-instruct-v0.2.Q4_K_M.gguf",
            "mistral-small3.1": "hf://bartowski/mistralai_Mistral-Small-3.1-24B-Instruct-2503-GGUF/mistralai_Mistral-Small-3.1-24B-Instruct-2503-IQ2_M.gguf",
            "mistral-small3.1:24b": "hf://bartowski/mistralai_Mistral-Small-3.1-24B-Instruct-2503-GGUF/mistralai_Mistral-Small-3.1-24B-Instruct-2503-IQ2_M.gguf",
            "mistral:7b": "huggingface://TheBloke/Mistral-7B-Instruct-v0.2-GGUF/mistral-7b-instruct-v0.2.Q4_K_M.gguf",
            "mistral:7b-v1": "huggingface://TheBloke/Mistral-7B-Instruct-v0.1-GGUF/mistral-7b-instruct-v0.1.Q5_K_M.gguf",
            "mistral:7b-v2": "huggingface://TheBloke/Mistral-7B-Instruct-v0.2-GGUF/mistral-7b-instruct-v0.2.Q4_K_M.gguf",
            "mistral:7b-v3": "huggingface://MaziyarPanahi/Mistral-7B-Instruct-v0.3-GGUF/Mistral-7B-Instruct-v0.3.Q4_K_M.gguf",
            "mistral_code_16k": "huggingface://TheBloke/Mistral-7B-Code-16K-qlora-GGUF/mistral-7b-code-16k-qlora.Q4_K_M.gguf",
            "mistral_codealpaca": "huggingface://TheBloke/Mistral-7B-codealpaca-lora-GGUF/mistral-7b-codealpaca-lora.Q4_K_M.gguf",
            "mixtao": "huggingface://MaziyarPanahi/MixTAO-7Bx2-MoE-Instruct-v7.0-GGUF/MixTAO-7Bx2-MoE-Instruct-v7.0.Q4_K_M.gguf",
            "openchat": "huggingface://TheBloke/openchat-3.5-0106-GGUF/openchat-3.5-0106.Q4_K_M.gguf",
            "openorca": "huggingface://TheBloke/Mistral-7B-OpenOrca-GGUF/mistral-7b-openorca.Q4_K_M.gguf",
            "phi2": "huggingface://MaziyarPanahi/phi-2-GGUF/phi-2.Q4_K_M.gguf",
            "qwen2.5vl": "hf://ggml-org/Qwen2.5-VL-32B-Instruct-GGUF",
            "qwen2.5vl:2b": "hf://ggml-org/Qwen2.5-VL-2B-Instruct-GGUF",
            "qwen2.5vl:32b": "hf://ggml-org/Qwen2.5-VL-32B-Instruct-GGUF",
            "qwen2.5vl:3b": "hf://ggml-org/Qwen2.5-VL-3B-Instruct-GGUF",
            "qwen2.5vl:7b": "hf://ggml-org/Qwen2.5-VL-7B-Instruct-GGUF",
            "smollm:135m": "ollama://smollm:135m",
            "smolvlm": "hf://ggml-org/SmolVLM-500M-Instruct-GGUF",
            "smolvlm:256m": "hf://ggml-org/SmolVLM-256M-Instruct-GGUF",
            "smolvlm:2b": "hf://ggml-org/SmolVLM-Instruct-GGUF",
            "smolvlm:500m": "hf://ggml-org/SmolVLM-500M-Instruct-GGUF",
            "tiny": "ollama://tinyllama"
        }
    },
    "Store": "/home/charles/.local/share/ramalama",
    "UseContainer": true,
    "Version": "0.9.2"
}
```

### Upstream Latest Release

No

### Additional information

I have stumbled on a [similar issue](https://github.com/mudler/LocalAI/issues/3437) on the LocalAI project. `sycl-ls` is not installed in the ramalama container and I did not know how to interact with the intel APIs from bash with the tools already installed in the container.
Passing the complete device names `--device /dev/dri/card1` and `--device /dev/dri/renderD128` along with `ramalama serve` did not help.
