### ISSUE TITLE
wrong krunkit warning when no models yet running?

### ISSUE THREAD

**Issue by maxandersen** [containers/ramalama#301]
when I run `ramalama list` I get warning about not using krunkit. (`Warning: podman needs to be configured to use krunkit for AI Workloads, running without containers`)

if i run `podman machine info` i says vmtype applehv which uses krunkit.

```
podman machine info
host:
    arch: arm64
    currentmachine: ""
    defaultmachine: ""
    eventsdir: /var/folders/mm/z7zzmyl15bd8byr8vsdxf1740000gn/T/storage-run-501/podman
    machineconfigdir: /Users/manderse/.config/containers/podman/machine/applehv
    machineimagedir: /Users/manderse/.local/share/containers/podman/machine/applehv
    machinestate: ""
    numberofmachines: 0
    os: darwin
    vmtype: applehv
version:
    apiversion: 5.2.0
    version: 5.2.0
    goversion: go1.22.5
    gitcommit: b22d5c61eef93475413724f49fd6a32980d2c746
    builttime: Fri Aug  2 14:05:53 2024
    built: 1722600353
    osarch: darwin/arm64
    os: darwin
```

looking in the code the test done is running `podman machine list` which is empty on my machine.
